### PR TITLE
Fixes #157

### LINKED ISSUE #157: Reduce Sensitivity doesn't work on 1.21.9
Zooming in doesn't reduce camera speed when "Reduce Sensitivity" is enabled.

Image

### PR DESCRIPTION
**Pull request by JTK222**
Replaced Injection mixins with WrapOperation mixins.
Not really sure why the previous ones broke, they seemed correct.

### CODE REVIEW

File: mod_fabric/src/main/java/io/github/ennuil/ok_zoomer/mixin/fabric/MouseHandlerMixin.java [hunk 1]
```diff
@@ -27,20 +29,24 @@ private void captureMouseSensitivity(double movementTime, CallbackInfo ci, @Loca
...
 			double zoomDivisor = Zoom.isZooming() ? Zoom.getZoomDivisor() : 1.0;
 			double transitionDivisor = Zoom.getTransitionMode().getInternalMultiplier();
-			i.set(Zoom.getMouseModifier().applyXModifier(i.get(), f, movementTime, zoomDivisor, transitionDivisor));
-			j.set(Zoom.getMouseModifier().applyYModifier(j.get(), f, movementTime, zoomDivisor, transitionDivisor));
+			original.call(instance,
+				Zoom.getMouseModifier().applyXModifier(x, f, movementTime, zoomDivisor, transitionDivisor),
+				Zoom.getMouseModifier().applyYModifier(y, f, movementTime, zoomDivisor, transitionDivisor)
+			);
+		}else{
+			original.call(instance, x, y);
```
Comment (EnnuiL) [inline mod_fabric/src/main/java/io/github/ennuil/ok_zoomer/mixin/fabric/MouseHandlerMixin.java]:
```suggestion
		} else {
			original.call(instance, x, y);
```

File: mod_norge/src/main/java/io/github/ennuil/ok_zoomer/mixin/norge/MouseHandlerMixin.java [hunk 2]
```diff
@@ -1,29 +1,34 @@
...
 			double zoomDivisor = Zoom.isZooming() ? Zoom.getZoomDivisor() : 1.0;
 			double transitionDivisor = Zoom.getTransitionMode().getInternalMultiplier();
-			d0.set(Zoom.getMouseModifier().applyXModifier(d0.get(), d4, movementTime, zoomDivisor, transitionDivisor));
-			d1.set(Zoom.getMouseModifier().applyYModifier(d1.get(), d4, movementTime, zoomDivisor, transitionDivisor));
+			original.call(instance,
+				Zoom.getMouseModifier().applyXModifier(x, cursorSpeed, movementTime, zoomDivisor, transitionDivisor),
+				Zoom.getMouseModifier().applyYModifier(y, cursorSpeed, movementTime, zoomDivisor, transitionDivisor)
+			);
+		}e lse{
+			original.call(instance, x, y);
```
Comment (EnnuiL) [inline mod_norge/src/main/java/io/github/ennuil/ok_zoomer/mixin/norge/MouseHandlerMixin.java]: I would be shocked if Java considered this valid (it doesn't)
```suggestion
		} else {
			original.call(instance, x, y);
```

**Review by EnnuiL — CHANGES_REQUESTED** [review]
There are only a few small fixes needed;

I do have to say though: I recall not going with `@ModifyArgs` here because I wanted to modify the locals themselves for better compatibility; I will be merging this though, I'm too exhausted to cook something up myself

**Comment by JTK222** [comment]
> There are only a few small fixes needed;
> 
> I do have to say though: I recall not going with `@ModifyArgs` here because I wanted to modify the locals themselves for better compatibility; I will be merging this though, I'm too exhausted to cook something up myself

That's why I used WrapOperation, it's a MixinExtras addition 
(which is shipped by both Fabric and NeoForge and adds the @Local annotation)
And it does exactly what your mixins achieved, they are stackable and specifically designed for compatibility.
(ModifyArgs should also have relative high compatabilty, but also creates a lot of overhead and has some limtations on local captures)

**Comment by EnnuiL** [comment]
> That's why I used WrapOperation, it's a MixinExtras addition (which is shipped by both Fabric and NeoForge and adds the `@Local` annotation) And it does exactly what your mixins achieved, they are stackable and specifically designed for compatibility. (ModifyArgs should also have relative high compatabilty, but also creates a lot of overhead and has some limtations on local captures)

Oh no, that's not the issue, the issue is that I was intentionally modifying the local variables in a way where after the modification, all code that uses it would have used it. `@WrapOperation` meanwhile acts as an easier version of `@ModifyArgs` and only modifies the parameters of a method call, not the variables themselves

Anyway, I'll be merging this after testing this

**Comment by EnnuiL** [comment]
Everything's working out! Thanks for the PR
